# Generated by Django 4.2.5 on 2023-09-25 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0005_alter_book_rental_price_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='rental',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
