# Generated by Django 4.2.5 on 2023-09-25 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0007_rename_rental_book_total_rental'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='total_rental',
            new_name='rental_total',
        ),
    ]
